### ISSUE TITLE
data cleaning - job category, races - "totals"

### ISSUE THREAD

**Issue by joitng** [UBC-InfoVis/447-materials#1]
some of the rows seem to be for aggregated data, there are data points with "totals" and "previous totals" as the job category which... doesn't seem right.

**Comment by fmnguyen** [comment]
What data file is this with respect to?

**Comment by joitng** [comment]
@fmnguyen Oh, sorry, this was just for us to keep track of for data cleaning! It's for the EEO1_data.csv data file.

**Comment by joitng** [comment]
OOPS!! Wrong repo. So sorry!
